spring.datasource.url=jdbc:postgresql://localhost:5432/medicore_auth
spring.datasource.username=postgres
spring.datasource.password=postgres
security.jwt.secret=****
security.jwt.access-token-minutes=**
security.jwt.refresh-token-days=*
